name: deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - uses: docker/setup-qemu-action@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_IAM_ROLE }}
          aws-region: ap-northeast-1
      - run: make build
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: terraform output
      - run: tar cf layers.tar *
        if: always()
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: layers.tar
          path: layers.tar
